name: PR Validation

on:
  pull_request:

jobs:
  deployment-check:
    name: Verify Static Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static export
        run: npm run build
        env:
          GITHUB_PAGES: true
          NEXT_PUBLIC_REPOSITORY_NAME: ${{ github.event.repository.name }}

      - name: Verify export output
        run: |
          test -d out
          test -f out/index.html
